* NumPy (short for Numerical Python) provides an efficient interface to store and operate on dense data buffers.
* NumPy arrays are like Python's built-in list type, but NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size. 
* It's a homogenous data storage
* It's mutable

In [1]:
l = [1,'hello',5.5]
# each element points to a piece of memory

In [2]:
import numpy as np

In [6]:
#Creating a numpy array from list
a = np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
a[1]

2

In [9]:
a[1]=99

In [10]:
a

array([ 1, 99,  3,  4,  5])

In [12]:
#a[2] = 'abc'
#This won't work, since numpy is homogenous data storage

In [13]:
data = np.array([ [1,2,3], [4,5,6], [7,8,9]])

In [14]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
data.shape

(3, 3)

In [16]:
a.shape

(5,)

In [17]:
a[2:5]

array([3, 4, 5])

In [18]:
a[::-1]

array([ 5,  4,  3, 99,  1])

In [25]:
#Makes a separate copy of the data
b = a.copy()

In [26]:
b[3] = 1000

In [27]:
a

array([ 1, 99,  3,  4,  5])

In [28]:
b

array([   1,   99,    3, 1000,    5])

#### Reshaping of Data

In [29]:
data = np.arange(10)

In [30]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
data[::-1].reshape((2,5))
# data did not change
# it returned a new data with different dimension

array([[9, 8, 7, 6, 5],
       [4, 3, 2, 1, 0]])

In [35]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
data[: , np.newaxis].shape

(10, 1)

In [39]:
data.shape

(10,)

### Array Concatenation & Splitting

In [40]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [42]:
np.concatenate([x,y,x])

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [43]:
grid = np.array([ [1,2,3],[5,6,7]])

In [44]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [46]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

In [47]:
x = np.array([4,44,444])

In [48]:
grid

array([[1, 2, 3],
       [5, 6, 7]])

In [49]:
np.vstack([x,grid])

array([[  4,  44, 444],
       [  1,   2,   3],
       [  5,   6,   7]])

In [51]:
np.hstack([grid,grid])

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])

#### Splitting of arrays

In [52]:
x = [1,2,77,4,5,9,6,7,7,9]

In [55]:
a,b,c,d = np.split(x, [3,5,8])

In [56]:
a

array([ 1,  2, 77])

In [57]:
b

array([4, 5])

In [58]:
c

array([9, 6, 7])

In [59]:
d

array([7, 9])