In [1]:
import numpy as np
%timeit np.arange(10000)


10000 loops, best of 3: 19.7 µs per loop


In [2]:
%time
x = np.arange(10000)

Wall time: 0 ns


In [3]:
x

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [4]:
%timeit sum(x)

100 loops, best of 3: 2.67 ms per loop


In [5]:
%timeit np.sum(x)

The slowest run took 18.75 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 18.8 µs per loop


#### np.func are much faster than reguar python functions

In [6]:
x = np.array([-1,-3,4,5,7])

In [7]:
np.abs(x)

array([1, 3, 4, 5, 7])

In [8]:
np.sin(x)

array([-0.84147098, -0.14112001, -0.7568025 , -0.95892427,  0.6569866 ])

In [9]:
data = np.array([ [1,2,3], [4,5,6]])

In [10]:
np.sin(data)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [11]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
np.dot(data,data.T)

array([[14, 32],
       [32, 77]])

In [15]:
data.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### Advanced Ufunc Features

In [16]:
x = np.arange(5)

In [17]:
y = np.empty(5)

In [18]:
x

array([0, 1, 2, 3, 4])

In [19]:
y

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.multiply(x,10,y)

array([  0.,  10.,  20.,  30.,  40.])

In [21]:
y

array([  0.,  10.,  20.,  30.,  40.])

In [22]:
x * 10

array([ 0, 10, 20, 30, 40])

In [23]:
y = np.zeros(10)

In [24]:
np.power(2,x,out= y[::2])

array([  1.,   2.,   4.,   8.,  16.])

In [25]:
y

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.])

In [26]:
z = np.arange(10)

In [27]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
z[::2]

array([0, 2, 4, 6, 8])

#### Aggregates

In [29]:
a = np.arange(1,6)

In [30]:
np.add.reduce(a)

15

In [31]:
np.multiply.reduce(a)

120

In [32]:
np.add.accumulate(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [33]:
np.multiply.accumulate(a)

array([  1,   2,   6,  24, 120], dtype=int32)

#### Random number generation

In [34]:
import numpy as np

In [35]:
x = np.random.random(100)

In [36]:
np.sum(x)

49.637530863710261

In [37]:
d1 = np.random.randint(low=10,high=20,size=(5000,5000))

In [38]:
a = np.arange(10)

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.min(a)

0

In [42]:
np.argmin(a)
# argmin - index of minimal data
# argmax - index of maximum data

0

In [43]:
mat = np.random.randint(low=10,high=20, size=(6,6))

In [47]:
mat.max(axis=1)

array([19, 17, 18, 19, 17, 18])

In [46]:
mat

array([[12, 18, 18, 19, 13, 10],
       [17, 12, 12, 12, 17, 14],
       [13, 11, 15, 16, 12, 18],
       [19, 12, 11, 14, 10, 16],
       [15, 16, 14, 17, 12, 15],
       [18, 16, 16, 11, 11, 18]])

In [48]:
mat.max(axis=0)

array([19, 18, 18, 19, 17, 18])

In [49]:
mat.std()

2.7431170879174465

In [50]:
mat.mean()

14.444444444444445

In [51]:
mat.var()

7.5246913580246924

In [53]:
2.7431170879174465 * 2.7431170879174465

7.5246913580246915

In [54]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = np.arange(5,15)

In [58]:
a + b

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [59]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [62]:
np.zeros((6,6,6))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.

In [63]:
a = np.arange(10)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x = a[:,np.newaxis]

In [68]:
x.T

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [69]:
a.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.linspace(10,15,30)
# Generates 30 elements between 10 & 15

array([ 10.        ,  10.17241379,  10.34482759,  10.51724138,
        10.68965517,  10.86206897,  11.03448276,  11.20689655,
        11.37931034,  11.55172414,  11.72413793,  11.89655172,
        12.06896552,  12.24137931,  12.4137931 ,  12.5862069 ,
        12.75862069,  12.93103448,  13.10344828,  13.27586207,
        13.44827586,  13.62068966,  13.79310345,  13.96551724,
        14.13793103,  14.31034483,  14.48275862,  14.65517241,
        14.82758621,  15.        ])

#### Comparision Opeartors

In [71]:
a = np.arange(10)

In [75]:
a < 4
#This guy returns a mask array. True will b true for those which matches the criteria

array([ True,  True,  True,  True, False, False, False, False, False, False], dtype=bool)

In [76]:
a[a<4]

array([0, 1, 2, 3])

In [77]:
a[a %2 == 0]

array([0, 2, 4, 6, 8])

In [78]:
a == 4

array([False, False, False, False,  True, False, False, False, False, False], dtype=bool)

In [79]:
a = np.array([5,4,3,55,7])

In [80]:
b = a

In [83]:
b[1] = 888
# a & b both will change, since both of them are sharing memory

In [82]:
a

array([  5, 888,   3,  55,   7])

In [92]:
z = a.copy()
#because of the copy, a & z are differet piece of memory

In [89]:
z[1] = 88

In [90]:
z

array([ 5, 88,  3, 55,  7])

In [91]:
a

array([  5, 888,   3,  55,   7])

In [93]:
a.ndim

1

In [94]:
a = np.arange(10)

In [95]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
a = np.random.randint(low=10,high=20,size=(5,5))

In [97]:
a

array([[11, 19, 18, 13, 10],
       [14, 17, 19, 17, 12],
       [14, 12, 16, 18, 10],
       [12, 16, 16, 12, 16],
       [13, 13, 15, 19, 18]])

In [98]:
a < 15

array([[ True, False, False,  True,  True],
       [ True, False, False, False,  True],
       [ True,  True, False, False,  True],
       [ True, False, False,  True, False],
       [ True,  True, False, False, False]], dtype=bool)

In [103]:
mask = []
for i in range(5):
    mask.append([])
    for j in range(5):
        if i == j:
            mask[i].append(True)
        else:
            mask[i].append(False)
        
a[np.array(mask)]
        
        

array([11, 17, 16, 12, 18])

In [106]:
a[~(a > 13) & (a < 17)]

array([11, 13, 10, 12, 12, 10, 12, 12, 13, 13])

##### Sorting Arrays

In [107]:
data = np.random.randint(low=10,high=20,size=10)

In [108]:
data

array([10, 17, 12, 17, 14, 11, 10, 19, 10, 19])

In [111]:
np.sort(data)
#Return sorted data without modifying actual data

array([10, 10, 10, 11, 12, 14, 17, 17, 19, 19])

In [110]:
data

array([10, 17, 12, 17, 14, 11, 10, 19, 10, 19])

In [114]:
data.sort()
# this is for doing inplace sorting

In [113]:
data

array([10, 10, 10, 11, 12, 14, 17, 17, 19, 19])

In [118]:
np.sort(a,axis=0)

array([[11, 12, 15, 12, 10],
       [12, 13, 16, 13, 10],
       [13, 16, 16, 17, 12],
       [14, 17, 18, 18, 16],
       [14, 19, 19, 19, 18]])