#### NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size

In [1]:
import numpy as np

In [3]:
data = np.array([1,2,3,4])

In [4]:
data = np.array(range(10))

In [5]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
data.argmin()

0

In [8]:
np.random.random()

0.19405716654455174

In [10]:
data = np.random.randint(low=10,high=100, size=10)

In [11]:
data

array([22, 24, 55, 96, 58, 92, 36, 38, 41, 52])

In [12]:
data.argmax()

3

In [13]:
np.max(data)

96

In [14]:
data.max()

96

In [15]:
x1 = np.random.randint(10,size=10)

In [16]:
x2 = np.random.randint(10, size=(3,4))

In [17]:
x2

array([[8, 2, 7, 6],
       [0, 7, 0, 0],
       [4, 0, 6, 1]])

In [20]:
x2.ndim

2

In [21]:
x2.size

12

In [22]:
x2.shape

(3L, 4L)

In [23]:
x2.dtype

dtype('int32')

In [26]:
np.array(['hellodd','worlsasasasd'])

array(['hellodd', 'worlsasasasd'], 
      dtype='|S12')

In [28]:
x2[1][2]

0

In [30]:
x2[-1]

array([4, 0, 6, 1])

In [31]:
x2[2,1]

0

In [32]:
x2

array([[8, 2, 7, 6],
       [0, 7, 0, 0],
       [4, 0, 6, 1]])

In [33]:
x2[2,1] = 9999

In [34]:
x2

array([[   8,    2,    7,    6],
       [   0,    7,    0,    0],
       [   4, 9999,    6,    1]])

In [36]:
x1

array([9, 4, 6, 4, 3, 2, 7, 0, 0, 9])

In [37]:
x1[2:8:2]

array([6, 3, 7])

In [38]:
x1[:5]

array([9, 4, 6, 4, 3])

In [39]:
x1[4:8]

array([3, 2, 7, 0])

In [40]:
x2

array([[   8,    2,    7,    6],
       [   0,    7,    0,    0],
       [   4, 9999,    6,    1]])

In [48]:
x2[1, 2:4]

array([0, 0])

In [ ]:
x1.si