### Introduction
* Main objective is to contain homogenous multidimesion array
* Faster compared to Python List
* NumPy dimension is called axes

In [1]:
#### Basics

import numpy as np

In [2]:
a = np.arange(20)

In [3]:
type(a)

numpy.ndarray

In [4]:
#To get num of dimension
a.ndim

1

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
a.shape

(20L,)

In [9]:
b = a.reshape(10,2)

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
b.shape

(10L, 2L)

In [11]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [12]:
b.dtype.name

'int32'

In [13]:
## Other way to create ndarray is using array function

In [14]:
c = np.array([2,4,5,77,8])

In [16]:
l = [3.9,45,6,7,7,44,4,3,3]
d = np.array(l)

In [17]:
d.dtype

dtype('float64')

In [18]:
strList = ['abc','def']
np.array(strList)

array(['abc', 'def'], 
      dtype='|S3')

In [20]:
np.zeros( (2,4,5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [22]:
np.ones( (2,2,3))

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [23]:
np.pi

3.141592653589793

In [25]:
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [26]:
np.sin(2)

0.90929742682568171

In [27]:
print a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

#### Basic Operations

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [32]:
b = np.arange(20,40)

In [33]:
b - a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20])

In [34]:
b

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [35]:
np.sin(b)

array([ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
       -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539])

In [37]:
x = np.array([ [1,2], [3,4]])

In [38]:
y = np.array([ [1,2], [3,4]])

In [39]:
x*y

array([[ 1,  4],
       [ 9, 16]])

In [40]:
x.dot(y)

array([[ 7, 10],
       [15, 22]])

In [41]:
np.dot(x,y)

array([[ 7, 10],
       [15, 22]])

In [43]:
## Random numbers generation

np.random.random( (2,3))

array([[ 0.19941969,  0.5357376 ,  0.39189004],
       [ 0.25329776,  0.16034291,  0.22584812]])