In [2]:
import numpy as np

In [2]:
x = np.array([-2,-1,0,1,2])

In [3]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [4]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [5]:
x = [1,2,3]

In [6]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [7]:
np.exp2(x)

array([ 2.,  4.,  8.])

In [8]:
np.power(3,x)

array([ 3,  9, 27])

In [9]:
x = [1,2,4,10]

In [10]:
np.log(x)

array([ 0.        ,  0.69314718,  1.38629436,  2.30258509])

In [11]:
np.log10(x)

array([ 0.        ,  0.30103   ,  0.60205999,  1.        ])

In [3]:
x = np.arange(1,6)

In [14]:
np.add.reduce(x)

15

In [15]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [18]:
np.multiply.reduce(x)

120

In [19]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [23]:
np.add.types

['??->?',
 'bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'ee->e',
 'ff->f',
 'dd->d',
 'gg->g',
 'FF->F',
 'DD->D',
 'GG->G',
 'Mm->M',
 'mm->m',
 'mM->M',
 'OO->O']

In [24]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [25]:
sum(x)

15

In [28]:
%timeit sum(np.random.randint(low=1, high=100, size=(10000)))

The slowest run took 9.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 2.86 ms per loop


In [29]:
%timeit np.sum(np.random.randint(low=1, high=100, size=(10000)))

1000 loops, best of 3: 346 µs per loop


In [31]:
%timeit min(np.random.randint(low=1, high=100, size=(10000)))

100 loops, best of 3: 2.55 ms per loop


In [32]:
%timeit np.min(np.random.randint(low=1, high=100, size=(10000)))

1000 loops, best of 3: 484 µs per loop


In [16]:
M = np.random.random((3,4))

In [18]:
np.random.random((5,5))

array([[ 0.27864055,  0.45274262,  0.58271371,  0.75877727,  0.02025945],
       [ 0.9702002 ,  0.08006546,  0.21778063,  0.19176186,  0.60318717],
       [ 0.91754872,  0.63350851,  0.11026792,  0.50330105,  0.13178614],
       [ 0.22217343,  0.22619998,  0.06109521,  0.73297996,  0.54948425],
       [ 0.58708237,  0.47931431,  0.22279963,  0.18390659,  0.62281331]])

In [34]:
M.min(axis=0)

array([ 0.02331609,  0.0279819 ,  0.35949429,  0.02072913])

In [35]:
M

array([[ 0.02331609,  0.46225827,  0.66144571,  0.58056724],
       [ 0.50721769,  0.68436084,  0.54182006,  0.02072913],
       [ 0.18260487,  0.0279819 ,  0.35949429,  0.59531335]])

In [38]:
np.all(np.array([1,2,3,0]))

False

In [19]:
np.min(M)

0.011314069362442725

In [20]:
M.min()

0.011314069362442725

In [21]:
np.all(M)

True

In [22]:
np.any(M)

True

In [23]:
M.shape

(3, 4)

In [24]:
M

array([[ 0.69830495,  0.37486499,  0.71570538,  0.45955302],
       [ 0.05031002,  0.46608175,  0.34393939,  0.85529627],
       [ 0.55209916,  0.01131407,  0.06375162,  0.93075978]])

In [25]:
M.reshape((2,6))

array([[ 0.69830495,  0.37486499,  0.71570538,  0.45955302,  0.05031002,
         0.46608175],
       [ 0.34393939,  0.85529627,  0.55209916,  0.01131407,  0.06375162,
         0.93075978]])

In [26]:
M

array([[ 0.69830495,  0.37486499,  0.71570538,  0.45955302],
       [ 0.05031002,  0.46608175,  0.34393939,  0.85529627],
       [ 0.55209916,  0.01131407,  0.06375162,  0.93075978]])

In [27]:
np.reshape(M,(2,6))

array([[ 0.69830495,  0.37486499,  0.71570538,  0.45955302,  0.05031002,
         0.46608175],
       [ 0.34393939,  0.85529627,  0.55209916,  0.01131407,  0.06375162,
         0.93075978]])

In [28]:
x = np.arange(10)

In [32]:
x.shape

(10,)

In [31]:
x[:,np.newaxis].shape

(10, 1)

In [34]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
fit([ [1,2], [2,4], [5,5] ])