#### NumPy arrays provide much more efficient storage and data operations as the arrays grow larger in size
* Mutable
* Homogenous
* Implemented using C
* List etc are more generic
* In list, your data is referenced but in numpy, they are hold up in memory

In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [4]:
data = np.array(range(10))

In [5]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
data.argmin()

0

In [8]:
np.random.random()

0.19405716654455174

In [3]:
data = np.random.randint(low=10,high=100, size=10)

In [4]:
data

array([92, 71, 93, 23, 63, 62, 64, 62, 82, 94])

In [7]:
data.argmax()
data.max()

94

In [8]:
np.max(data)

94

In [14]:
data.max()

96

In [9]:
x1 = np.random.randint(10,size=10)
x1

array([4, 5, 0, 6, 1, 6, 3, 6, 0, 2])

In [13]:
x2 = np.random.randint(10, size=(3,4,5))

In [14]:
x2

array([[[6, 2, 7, 4, 3],
        [7, 6, 8, 6, 9],
        [5, 6, 8, 6, 2],
        [6, 8, 9, 9, 3]],

       [[6, 4, 6, 0, 9],
        [3, 9, 4, 1, 0],
        [1, 0, 0, 3, 4],
        [4, 5, 6, 8, 0]],

       [[1, 2, 3, 7, 1],
        [4, 0, 4, 7, 5],
        [5, 1, 3, 8, 8],
        [6, 6, 2, 6, 7]]])

In [15]:
x2.ndim

3

In [16]:
x2.size

60

In [17]:
x2.shape

(3, 4, 5)

In [23]:
x2.dtype

dtype('int32')

In [26]:
np.array(['hellodd','worlsasasasd'])

array(['hellodd', 'worlsasasasd'], 
      dtype='|S12')

In [19]:
x2[1][2][-1]

4

In [30]:
x2[-1]

array([4, 0, 6, 1])

In [31]:
x2[2,1]

0

In [20]:
x2

array([[[6, 2, 7, 4, 3],
        [7, 6, 8, 6, 9],
        [5, 6, 8, 6, 2],
        [6, 8, 9, 9, 3]],

       [[6, 4, 6, 0, 9],
        [3, 9, 4, 1, 0],
        [1, 0, 0, 3, 4],
        [4, 5, 6, 8, 0]],

       [[1, 2, 3, 7, 1],
        [4, 0, 4, 7, 5],
        [5, 1, 3, 8, 8],
        [6, 6, 2, 6, 7]]])

In [21]:
x2[2,1,1] = 9999

In [22]:
x2

array([[[   6,    2,    7,    4,    3],
        [   7,    6,    8,    6,    9],
        [   5,    6,    8,    6,    2],
        [   6,    8,    9,    9,    3]],

       [[   6,    4,    6,    0,    9],
        [   3,    9,    4,    1,    0],
        [   1,    0,    0,    3,    4],
        [   4,    5,    6,    8,    0]],

       [[   1,    2,    3,    7,    1],
        [   4, 9999,    4,    7,    5],
        [   5,    1,    3,    8,    8],
        [   6,    6,    2,    6,    7]]])

In [23]:
x1

array([4, 5, 0, 6, 1, 6, 3, 6, 0, 2])

In [37]:
x1[2:8:2]

array([6, 3, 7])

In [38]:
x1[:5]

array([9, 4, 6, 4, 3])

In [39]:
x1[4:8]

array([3, 2, 7, 0])

In [40]:
x2

array([[   8,    2,    7,    6],
       [   0,    7,    0,    0],
       [   4, 9999,    6,    1]])

In [48]:
x2[1, 2:4]

array([0, 0])

In [ ]:
x1.si