#### Tensorflow Operations (Ops)
* They take any number of inputs & produce any number of outputs
* Examples are multiplication & addition - they take inputs & produce outputs

#### Tensorflow Constants & Variables ( Source Ops ) 
* They take no inputs

#### Tensors
* Similar to NumPy, tensors have type & shape
* The TensorFlow Operations takes Tensors as inputs


In [1]:
import tensorflow as tf

In [2]:
tf.abs(-9)

<tf.Tensor 'Abs:0' shape=() dtype=int32>

In [4]:
import numpy as np
from sklearn.datasets import fetch_california_housing

In [5]:
housing = fetch_california_housing()

downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to C:\Users\ZekeLabs\scikit_learn_data


In [7]:
m,n = housing.data.shape

In [16]:
m

20640

In [13]:
np.array([[[1,2,3]]]).shape

(1, 1, 3)

In [18]:
housing_data_plus_bias = np.c_[np.ones((m,1)),housing.data]
#help(np.c_)

In [19]:
X = tf.constant(housing_data_plus_bias, dtype=tf.float32, name="X")

In [20]:
X

<tf.Tensor 'X:0' shape=(20640, 9) dtype=float32>

In [21]:
housing_data_plus_bias

array([[   1.        ,    8.3252    ,   41.        , ...,    2.55555556,
          37.88      , -122.23      ],
       [   1.        ,    8.3014    ,   21.        , ...,    2.10984183,
          37.86      , -122.22      ],
       [   1.        ,    7.2574    ,   52.        , ...,    2.80225989,
          37.85      , -122.24      ],
       ..., 
       [   1.        ,    1.7       ,   17.        , ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.        ,    1.8672    ,   18.        , ...,    2.12320917,
          39.43      , -121.32      ],
       [   1.        ,    2.3886    ,   16.        , ...,    2.61698113,
          39.37      , -121.24      ]])

In [22]:
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")

In [24]:
housing.target.reshape(-1, 1)

array([[ 4.526],
       [ 3.585],
       [ 3.521],
       ..., 
       [ 0.923],
       [ 0.847],
       [ 0.894]])

In [25]:
XT = tf.transpose(X)

In [29]:
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)),XT),y)

In [30]:
with tf.Session() as sess:
    theta_val = theta.eval()

In [31]:
theta_val

array([[ -3.74651413e+01],
       [  4.35734153e-01],
       [  9.33829229e-03],
       [ -1.06622010e-01],
       [  6.44106984e-01],
       [ -4.25131839e-06],
       [ -3.77322501e-03],
       [ -4.26648885e-01],
       [ -4.40514028e-01]], dtype=float32)